<?php

declare(strict_types=1);

namespace BeastBytes\Router\Register;

use BeastBytes\Router\Register\DTO\Group;

/**
 * A WriterInterface implementation takes the tree structure generated by the RouterRegister Parser
 * and generates framework specific router configuration.
 */
interface WriterInterface
{
    /**
     * @var Group[] $groups The groups tree
     *  @var string $path The path to write generated configuration files to
     */
    public function write(array $groups, string $path): void;
}